<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="41" started-at="2021-04-05T11:04:34Z" finished-at="2021-04-05T11:04:34Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="41" started-at="2021-04-05T11:04:34Z" finished-at="2021-04-05T11:04:34Z">
      <class name="org.tool.Parallel1">
        <test-method status="PASS" signature="tc1()[pri:0, instance:org.tool.Parallel1@4678c730]" name="tc1" duration-ms="9" started-at="2021-04-05T11:04:34Z" finished-at="2021-04-05T11:04:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc1 -->
        <test-method status="FAIL" signature="tc2()[pri:0, instance:org.tool.Parallel1@4678c730]" name="tc2" duration-ms="4" started-at="2021-04-05T11:04:34Z" finished-at="2021-04-05T11:04:34Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at org.tool.Parallel1.tc2(Parallel1.java:17)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc2 -->
        <test-method status="PASS" signature="tc3()[pri:0, instance:org.tool.Parallel1@4678c730]" name="tc3" duration-ms="1" started-at="2021-04-05T11:04:34Z" finished-at="2021-04-05T11:04:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc3 -->
      </class> <!-- org.tool.Parallel1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
